### ISSUE TITLE
TypeError: this.remoteInfo.getStreamByMediaId is not a function

### ISSUE THREAD

**Issue by kelexel** [medooze/sfu#14]
Hello

I am trying to install the SFU demo, but I have a few issues;

1) The file www/js/sfu.js connect() method refers to this.key, which is undefined. Easily fixable, although I have no clue what the key is supposed to do.

2) Which led me to being able to pseudo connect, albeit an error in the server console:
2020-04-06T15:34:08.055Z [INFO ] rooms[fff]::participants[0] init
TypeError: this.remoteInfo.getStreamByMediaId is not a function
    at SDPManagerUnified.processRemoteDescription (/Users/rud/Desktop/medooze/sfu/node_modules/medooze-media-server/lib/SDPManagerUnified.js:319:39)
    at Participant.init (/Users/rud/Desktop/medooze/sfu/lib/Participant.js:124:16)
    at TransactionManager.<anonymous> (/Users/rud/Desktop/medooze/sfu/index.js:167:33)
    at TransactionManager.emit (events.js:198:13)
    at WebSocketConnection.TransactionManager.listener (/Users/rud/Desktop/medooze/sfu/node_modules/transaction-manager/index.js:85:12)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.processFrame (/Users/rud/Desktop/medooze/sfu/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /Users/rud/Desktop/medooze/sfu/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:61:11)
connection:onclose
2020-04-06T15:34:08.074Z [INFO ] rooms[fff]::participants[0] stop
2020-04-06T15:34:08.074Z [INFO ] rooms[fff]::participants[0] onstopped

Thus my humble question, is this demo running with latest medooze-media-server ..?

Thank you :)

**Comment by murillo128** [comment]
Could you check what is the version of the `medooze-media-serer` and update to latest if not in it already?

**Comment by kelexel** [comment]
@murillo128 : Thank you for your reply.
I am using latest medooze-media-server-0.87.0.tgz, built myself and installed manually..
Also, using node v10.19.0 on OSX 10.15.4.
I'm available if you want more details

**Comment by murillo128** [comment]
can you check the version of the semantic-sdp?
`getStreamByMediaId` is defined here:
https://github.com/medooze/semantic-sdp-js/blob/bb8b9a1867c2981fcd03b28ccfc8325c27d50392/lib/SDPInfo.js#L453

Can you also print the contents of `this.remoteInfo`?
